import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar.js";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`container mx-auto mt-4 md:mt-8 px-4 md:8 ${montserrat.variable} antialiased`}
      >
        <Navbar />
        <div className="mt-8">
          {children}
        </div>
      </body>
    </html>
  );
}
